Default: &defaults
  database: DaitanSkell.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: DaitanSkell_test.sqlite3
  <<: *defaults

Staging:
  database: DaitanSkell_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: DaitanSkell_production.sqlite3
  poolsize: 100
  <<: *defaults
